#!/bin/bash

# Set these in each environment
alias run_tests='echo "Run tests"'

run_tests

# From http://www.commandlinefu.com/commands/view/6019/have-a-random-cow-say-a-random-thing
#  - needs cowsay and fortune
fortune | cowsay -f $(ls /usr/share/cowsay/cows/ | shuf -n1)
